-- ==============================================================================
-- SmartSend AI - Supabase PostgreSQL Schema & Initial Seed
-- Paste this script into Supabase SQL Editor:
-- https://supabase.com/dashboard/project/joqherfotksjlpyztcdc/sql
-- ==============================================================================

-- 1. Groups Table
CREATE TABLE IF NOT EXISTS public.groups_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  color TEXT DEFAULT '#6366F1',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Contacts Table
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  group_id BIGINT REFERENCES public.groups_table(id) ON DELETE SET NULL,
  custom_fields JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  prompt TEXT,
  subject TEXT,
  body TEXT NOT NULL,
  short_version TEXT,
  cta TEXT,
  channel TEXT NOT NULL DEFAULT 'email',
  recipient_count INTEGER DEFAULT 0,
  recipients_json TEXT DEFAULT '[]',
  status TEXT DEFAULT 'sent',
  is_demo INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Scheduled Messages Table
CREATE TABLE IF NOT EXISTS public.scheduled_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT REFERENCES public.messages(id) ON DELETE CASCADE,
  channel TEXT NOT NULL DEFAULT 'email',
  subject TEXT,
  body TEXT NOT NULL,
  recipients_json TEXT DEFAULT '[]',
  scheduled_time TIMESTAMPTZ NOT NULL,
  timezone TEXT DEFAULT 'UTC',
  status TEXT DEFAULT 'scheduled',
  is_demo INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Message Delivery Logs Table
CREATE TABLE IF NOT EXISTS public.message_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT,
  contact_id BIGINT,
  contact_name TEXT,
  contact_target TEXT,
  channel TEXT NOT NULL DEFAULT 'email',
  rendered_subject TEXT,
  rendered_body TEXT NOT NULL,
  status TEXT NOT NULL,
  is_demo INTEGER DEFAULT 1,
  error_message TEXT,
  delivery_timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Enable Row Level Security (RLS) & Grant Access for Anon / Authenticated
ALTER TABLE public.groups_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access groups_table" ON public.groups_table;
CREATE POLICY "Public full access groups_table" ON public.groups_table FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access contacts" ON public.contacts;
CREATE POLICY "Public full access contacts" ON public.contacts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access messages" ON public.messages;
CREATE POLICY "Public full access messages" ON public.messages FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access scheduled_messages" ON public.scheduled_messages;
CREATE POLICY "Public full access scheduled_messages" ON public.scheduled_messages FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access message_logs" ON public.message_logs;
CREATE POLICY "Public full access message_logs" ON public.message_logs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access settings" ON public.settings;
CREATE POLICY "Public full access settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

-- 8. Seed Groups
INSERT INTO public.groups_table (name, description, color) VALUES
  ('VIP Clients', 'High-touch enterprise clients and partners', '#6366F1'),
  ('Product Beta', 'Early access beta testers and power users', '#10B981'),
  ('AI Workshop Students', 'Attendees for hands-on generative AI cohort', '#F59E0B')
ON CONFLICT (name) DO NOTHING;

-- 9. Seed Contacts
INSERT INTO public.contacts (name, email, phone, group_id, custom_fields) VALUES
  ('Mukesh Varma', 'mukeshvarma95117@gmail.com', '+91 98765 43210', 1, '{"event": "AI Workshop", "date": "tomorrow", "time": "10:00 AM", "company": "SmartSend AI", "city": "Bengaluru"}'),
  ('Alex Johnson', 'alex.j@enterprise.io', '+1 415 555 2671', 2, '{"company": "Acme Corp", "role": "CTO", "city": "San Francisco"}'),
  ('Sarah Connor', 'sarah.c@cyberdyne.io', '+1 310 555 9821', 1, '{"city": "Los Angeles", "role": "Security Lead"}')
ON CONFLICT DO NOTHING;

-- 10. Seed Initial Settings
INSERT INTO public.settings (key, value) VALUES
  ('demo_mode', 'false'),
  ('email_provider', 'resend'),
  ('resend_api_key', ''),
  ('resend_from', 'SmartSend AI <notifications@smartsendai.online>'),
  ('timezone', 'Asia/Kolkata'),
  ('default_channel', 'email'),
  ('default_tone', 'Professional'),
  ('default_language', 'English')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
